name: Build Zyde (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build (comma-separated: windows, macos, linux)'
        required: true
        default: 'windows'

jobs:
  build-windows:
    name: Build Zyde for Windows (x64)
    runs-on: windows-2022  # Uses Windows 2022 runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Required for node-gyp

      - name: Install Visual Studio Build Tools
        run: |
          $InstallerPath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe"
          Start-Process -FilePath $InstallerPath -ArgumentList @(
            "modify",
            "--installPath", "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools",
            "--add", "Microsoft.VisualStudio.Workload.NativeDesktop",
            "--add", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
            "--add", "Microsoft.VisualStudio.Component.Windows10SDK.20348",
            "--add", "Microsoft.VisualStudio.Component.VC.ATL",
            "--add", "Microsoft.VisualStudio.Component.VC.MFC",
            "--add", "Microsoft.VisualStudio.Component.VC.MFC.Spectre",
            "--add", "Microsoft.VisualStudio.Component.VC.Tools.x64.x86.Spectre",
            "--add", "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
            "--add", "Microsoft.VisualStudio.Component.VC.CMake.Project",
            "--add", "Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset",
            "--add", "Microsoft.VisualStudio.Component.Windows10SDK.22621",
            "--add", "Microsoft.VisualStudio.Component.VC.CoreIde",
            "--quiet", "--wait", "--norestart"
          ) -NoNewWindow -Wait
        shell: pwsh

      - name: Verify Installed Components
        run: |
          "Checking Installed Components..."
          & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products * -format json | ConvertFrom-Json | Out-String
        shell: pwsh

      - name: Set up Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: '2022'
          arch: 'x64'

      - name: Configure NPM for MSVC
        run: |
          echo "msvs_version=2022" > $env:USERPROFILE\.npmrc
        shell: pwsh

      - name: Clean npm Cache
        run: npm cache clean --force
        shell: cmd

      - name: Install Required Dependencies
        run: |
          npm install
        shell: cmd

      - name: Build VS Code (Windows x64)
        run: npm run gulp vscode-win32-x64
        shell: cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-win32-x64
          path: .build/win32-x64  # Adjust if necessary
