name: Build VS Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build (comma-separated: windows, macos, linux)'
        required: true
        default: 'windows,macos,linux'

jobs:
  build-windows:
    name: Build Windows (x64)
    if: ${{ !inputs.platforms || contains(inputs.platforms, 'windows') }}
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: '2022'
          arch: 'x64'

      - name: Configure build environment
        run: |
          # Set environment variables for node-gyp
          echo "GYP_MSVS_VERSION=2022" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "npm_config_msvs_version=2022" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          # Create .npmrc file with VS version
          echo "msvs_version=2022" | Out-File -FilePath .npmrc -Encoding utf8

          # Check installed Visual Studio components
          Get-ChildItem "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC" -Recurse | Select-Object FullName

      - name: Install dependencies
        run: |
          npm install -g node-gyp
          npm install --no-optional

      - name: Build VS Code for Windows (x64)
        run: |
          npm run gulp vscode-win32-x64

      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-win32-x64
          path: .build/win32-x64

  build-macos:
    name: Build macOS
    if: ${{ !inputs.platforms || contains(inputs.platforms, 'macos') }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build VS Code for macOS
        run: |
          npm run gulp vscode-darwin-x64

      - name: Upload macOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-darwin-x64
          path: .build/darwin-x64

  build-linux:
    name: Build Linux
    if: ${{ !inputs.platforms || contains(inputs.platforms, 'linux') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3 fakeroot rpm
          npm install

      - name: Build VS Code for Linux
        run: |
          npm run gulp vscode-linux-x64

      - name: Upload Linux build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-linux-x64
          path: .build/linux-x64
