name: Build Zyde (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build (comma-separated: windows, macos, linux)'
        required: true
        default: 'windows'

jobs:
  build-windows:
    name: Build Zyde for Windows (x64)
    runs-on: windows-2022  # Uses Windows 2022 runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'npm'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: "2022"
          arch: "x64"

      - name: Install Visual Studio Build Tools with Required Components
        run: |
          choco install visualstudio2022buildtools --params `
            "--add Microsoft.VisualStudio.Workload.NativeDesktop `
            --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64.Spectre `
            --add Microsoft.VisualStudio.Component.VC.ATL.Spectre `
            --add Microsoft.VisualStudio.Component.VC.MFC.Spectre"
        shell: pwsh

      - name: Set Environment Variable for MSBuild
        run: echo "msvs_version=2022" >> $GITHUB_ENV
        shell: bash

      - name: Clean npm Cache
        run: npm cache clean --force
        shell: cmd

      - name: Install Required Dependencies
        run: |
          npm install
        shell: cmd

      - name: Build VS Code (Windows x64)
        run: |
          set VSCODE_ARCH=x64
          npm run gulp vscode-win32-x64
        shell: cmd

      - name: Debug: List Build Output
        run: dir /s .build\
        shell: cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zyde-win32-x64
          path: .build/win32-x64
          if-no-files-found: warn
