name: Build Zyde

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'npm'

      - name: Install VS Build Tools (C++ with Spectre-mitigated libs)
        shell: pwsh
        run: |
          choco install -y visualstudio2022buildtools --package-parameters `
            "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            --add Microsoft.VisualStudio.Component.Windows10SDK.19041 `
            --add Microsoft.VisualStudio.Component.Windows11SDK `
            --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest `
            --add Microsoft.VisualStudio.Component.VC.ATL.Spectre `
            --add Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre `
            --add Microsoft.VisualStudio.Component.VC.MFC.Spectre `
            --add Microsoft.VisualStudio.Component.VC.CoreBuildTools "

      - name: Set Up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install Python 3 (Required for Windows Build)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: npm install 

      - name: Build Zyde
        run: npm run gulp vscode-win32-x64  # Modify if you changed the gulp task name

      - name: Upload Zyde Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zyde-win32-x64
          path: .build/zyde-win32-x64
          retention-days: 7
