name: Build Zyde (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build (comma-separated: windows, macos, linux)'
        required: true
        default: 'windows'

jobs:
  build-windows:
    name: Build Zyde for Windows (x64)
    runs-on: windows-2022  # Uses Windows 2022 runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper version detection

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Required for node-gyp

      - name: Install Visual Studio Build Tools
        run: |
          # Download the Visual Studio installer bootstrapper if not available
          if (-not (Test-Path "$env:TEMP\vs_buildtools.exe")) {
            Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "$env:TEMP\vs_buildtools.exe"
          }

          # Install Build Tools with all required components
          Start-Process -FilePath "$env:TEMP\vs_buildtools.exe" -ArgumentList @(
            "--quiet",
            "--wait",
            "--norestart",
            "--nocache",
            "--installPath", """C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools""",
            "--add", "Microsoft.VisualStudio.Workload.VCTools",
            "--add", "Microsoft.VisualStudio.Workload.NativeDesktop",
            "--add", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
            "--add", "Microsoft.VisualStudio.Component.Windows10SDK.22621",
            "--add", "Microsoft.VisualStudio.Component.VC.ATL",
            "--add", "Microsoft.VisualStudio.Component.VC.ATLMFC",
            "--add", "Microsoft.VisualStudio.Component.VC.CMake.Project",
            "--add", "Microsoft.VisualStudio.Component.VC.CoreIde",
            "--add", "Microsoft.VisualStudio.Component.Windows11SDK.22621"
          ) -NoNewWindow -Wait
        shell: pwsh

      - name: Verify Installed Visual Studio Components
        run: |
          Write-Host "Checking Installed VS Components..."
          & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -products * -format json | ConvertFrom-Json | ForEach-Object { $_.installationPath }

          $msvcDir = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\"
          if (Test-Path $msvcDir) {
            Write-Host "VC Tools directory exists at: $msvcDir"
            Get-ChildItem $msvcDir -Directory | ForEach-Object { Write-Host "Found MSVC version: $($_.Name)" }
          } else {
            Write-Error "VC Tools directory not found at expected location: $msvcDir"
            exit 1
          }
        shell: pwsh

      - name: Set up Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: '2022'
          arch: 'x64'

      - name: Diagnostic - Verify C++ Compiler
        run: |
          echo "Checking C++ compiler..."
          where cl.exe
          cl.exe 2>&1 | findstr /C:"Microsoft"
          echo "VCTargetsPath: %VCTargetsPath%"
          echo "VCToolsInstallDir: %VCToolsInstallDir%"
          echo "VSINSTALLDIR: %VSINSTALLDIR%"
        shell: cmd

      - name: Configure NPM
        run: |
          npm config set msvs_version 2022
          npm config set python %PYTHON_PATH%
          npm config list
        shell: cmd

      - name: Clean npm Cache
        run: npm cache clean --force
        shell: cmd

      - name: Install Required Dependencies
        run: npm install
        shell: cmd

      - name: Build VS Code (Windows x64)
        run: |
          npm run gulp vscode-win32-x64
        shell: cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zyde-win32-x64
          path: .build/win32-x64
          if-no-files-found: error
